/**
 * 公开页的全部浏览器行为，内联直出，预算 ≤5KB（有 e2e 守着）。
 *
 * embedded() 闸门的由来：营销首页 hero 用 iframe 实时加载 /p/demo-illustrator 当首屏视觉，
 * 而本脚本末尾无条件上报 VIEW——等于首页每被打开一次就给该演示页记一次浏览。
 * 那个数字又被演示页自己的转化条当作「累计访问 N」的社会证明展示出来，
 * 于是首页流量在给自家示例页的证明数字灌水，同时污染统计后台。
 * frame-ancestors 只允许同源嵌入，因此「在框架里」等价于「这是我们自己的展示台」，一律不计数。
 */
export const PUBLIC_INTERACTION_SCRIPT = `(()=>{var timer;function embedded(){try{return window.top!==window.self}catch(_){return true}}function track(kind,blockId){if(embedded())return;var root=document.querySelector('[data-page-id]'),pageId=root&&root.getAttribute('data-page-id');if(!pageId)return;var payload=JSON.stringify(blockId?{pageId:pageId,blockId:blockId,kind:kind}:{pageId:pageId,kind:kind});try{if(navigator.sendBeacon&&navigator.sendBeacon('/api/e',new Blob([payload],{type:'application/json'})))return}catch(_){}if(window.fetch)fetch('/api/e',{method:'POST',headers:{'content-type':'application/json'},body:payload,keepalive:true}).catch(function(){})}window.__yl_e=function(kind,blockId){track(String(kind).toUpperCase(),blockId)};function fallback(value){var area=document.createElement('textarea');area.value=value;area.setAttribute('readonly','');area.style.cssText='position:fixed;opacity:0;pointer-events:none';document.body.appendChild(area);area.select();try{document.execCommand('copy')}catch(_){}area.remove();return Promise.resolve()}function copy(value){if(navigator.clipboard&&navigator.clipboard.writeText){return navigator.clipboard.writeText(value).catch(function(){return fallback(value)})}return fallback(value)}function toast(message){var node=document.querySelector('[data-public-toast]');if(!node)return;node.textContent=message;node.dataset.visible='true';clearTimeout(timer);timer=setTimeout(function(){node.dataset.visible='false'},1800)}document.addEventListener('click',function(event){var origin=event.target;if(!(origin instanceof Element))return;var tracked=origin.closest('[data-track]');if(tracked)window.__yl_e('CLICK',tracked.getAttribute('data-block-id')||undefined);var button=origin.closest('[data-copy]');if(!button)return;event.preventDefault();var value=button.getAttribute('data-copy')||'';if(!value)return;copy(value).then(function(){var label=button.querySelector('[data-copy-label]');if(label){var before=label.textContent;label.textContent='已复制';button.dataset.copied='true';setTimeout(function(){label.textContent=before;button.dataset.copied='false'},1500)}toast(button.getAttribute('data-toast')||'已复制')})});window.__yl_e('VIEW')})();`;
